#!/usr/bin/env bash
# Fine-tunes Qwen2.5-1.5B-Instruct with LoRA using llama.cpp.
# Produces a merged GGUF with the adapter baked in.
# Prerequisites:
#   - llama.cpp built with LLAMA_BUILD_EXAMPLES=ON (for train-text-lora)
#   - training/training.jsonl generated by prepare_datasets.py
# Usage:   bash training/train_lora.sh
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$HERE"

MODEL="model/Qwen2.5-1.5B-Instruct-Q4_K_M.gguf"
OUTPUT="model/Kanzu-Qwen2.5-1.5B-Q4_K_M-lora.gguf"
TRAINING_DATA="training/training.jsonl"

if [ ! -f "$MODEL" ]; then
    echo "error: $MODEL not found"
    exit 1
fi

if [ ! -f "$TRAINING_DATA" ]; then
    echo "error: $TRAINING_DATA not found. Run training/prepare_datasets.py first."
    exit 1
fi

# --- locate llama-cli ---
LLAMA_CLI="${KANZU_LLAMA_CLI:-./vendor/llama.cpp/build/bin/llama-cli}"
if command -v "$LLAMA_CLI" >/dev/null 2>&1; then
    :
elif [ -f "${LLAMA_CLI}.exe" ]; then
    LLAMA_CLI="${LLAMA_CLI}.exe"
else
    echo "error: llama-cli not found at $LLAMA_CLI"
    echo "  Run scripts/setup_llama_cpp.sh or set KANZU_LLAMA_CLI."
    exit 1
fi

THREADS="${KANZU_THREADS:-4}"

# --- print plan ---
LINES=$(wc -l < "$TRAINING_DATA")
echo "Training LoRA adapter ..."
echo "  Model:       $MODEL"
echo "  Data:        $TRAINING_DATA ($LINES lines)"
echo "  Output:      $OUTPUT"
echo "  Threads:     $THREADS"
echo "  LoRA rank:   16"
echo "  LoRA alpha:  32"
echo "  Epochs:      2"
echo "  LR:          2e-4"
echo "  Cutoff:      256 tokens"
echo "  Context:     2048"
echo ""

# --- train ---
"$LLAMA_CLI" train-text-lora \
    -m "$MODEL" \
    -f "$TRAINING_DATA" \
    -c 2048 \
    --lora-r 16 \
    --lora-alpha 32 \
    --epoch 2 \
    --lr 2e-4 \
    --cut-off 256 \
    -t "$THREADS" \
    --out-lora "training/kanzu-lora.bin" \
    --out-tied "$OUTPUT" 2>&1 || {
    echo ""
    echo "If train-text-lora is not available, rebuild llama.cpp with:"
    echo "  cmake -DLLAMA_BUILD_EXAMPLES=ON .. && cmake --build . --target train-text-lora"
    exit 1
}

echo ""
echo "Training complete. Output: $OUTPUT"
echo "Re-verify with: go run ./cmd/kanzu doctor"