#!/usr/bin/env bash
# Fine-tunes Qwen2.5-1.5B-Instruct with LoRA using llama.cpp.
# Produces a merged GGUF with the adapter baked in.
# Prerequisites:
#   - llama.cpp built with LLAMA_BUILD_EXAMPLES=ON (for train-text-lora)
#   - training/training.jsonl generated by prepare_datasets.py
# Usage:   bash training/train_lora.sh
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$HERE"

MODEL="model/Qwen2.5-1.5B-Instruct-Q4_K_M.gguf"
OUTPUT="model/Kanzu-Qwen2.5-1.5B-Q4_K_M-lora.gguf"
TEMP_F16="/tmp/kanzu-f16/Qwen2.5-1.5B-Instruct-f16.gguf"
FINAL_Q4="/tmp/kanzu-f16/Kanzu-f16-Q4_K_M.gguf"
TRAINING_DATA="training/training.jsonl"

if [ ! -f "$MODEL" ]; then
    echo "error: $MODEL not found"
    exit 1
fi

if [ ! -f "$TRAINING_DATA" ]; then
    echo "error: $TRAINING_DATA not found. Run training/prepare_datasets.py first."
    exit 1
fi

# --- locate llama-finetune ---
LLAMA_FIN="${KANZU_LLAMA_FIN:-./vendor/llama.cpp/build/bin/llama-finetune}"
if command -v "$LLAMA_FIN" >/dev/null 2>&1; then
    FIN_CMD="$LLAMA_FIN"
elif [ -f "${LLAMA_FIN}.exe" ]; then
    FIN_CMD="${LLAMA_FIN}.exe"
else
    echo "error: llama-finetune not found at $LLAMA_FIN"
    echo "  Run scripts/setup_llama_cpp.sh or set KANZU_LLAMA_FIN."
    exit 1
fi

THREADS="${KANZU_THREADS:-4}"

# --- print plan ---
LINES=$(wc -l < "$TRAINING_DATA")
echo "Training LoRA adapter ..."
echo "  Model:       $MODEL"
echo "  Data:        $TRAINING_DATA ($LINES lines)"
echo "  Output:      $OUTPUT"
echo "  Threads:     $THREADS"
echo "  LoRA rank:   16"
echo "  LoRA alpha:  32"
echo "  Epochs:      2"
echo "  LR:          2e-4"
echo "  Cutoff:      256 tokens"
echo "  Context:     2048"
echo ""

# --- train ---
# This llama.cpp version provides 'llama-finetune' as a standalone binary.
# It is invoked directly (no subcommand). It performs full fine-tuning.
# Key flags:
#   -m  model path
#   -f  training data file (JSONL, one ChatML doc per line)
#   -c  context size
#   -t  threads
#   -epochs  number of epochs (default 2)
#   -lr  learning rate
#   -opt  optimizer (adamw or sgd)
#   -wd  weight decay
#   -val-split  validation split fraction
#   -o / --output  output file path
# LoRA flags (--lora-r, --lora-alpha, --out-lora, --out-tied) are NOT available.
# This script runs full fine-tuning as the available option.
"$FIN_CMD" \
    -m "$MODEL" \
    -f "$TRAINING_DATA" \
    -c 2048 \
    -t "$THREADS" \
    -epochs 2 \
    -lr 2e-5 \
    -opt adamw \
    -wd 0.01 \
    -val-split 0.05 \
    -o "$OUTPUT" 2>&1 || {
    echo ""
    echo "Training failed. llama-finetune ran but exited non-zero."
    echo "Check training output above for errors."
    echo "This llama.cpp version only supports full fine-tuning, not LoRA."
    echo "To try LoRA, a different llama.cpp build or external tooling is needed."
    exit 1
}

echo ""
echo "Training complete. Output: $OUTPUT"
echo "Re-verify with: go run ./cmd/kanzu doctor"